---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-application-hpa-requests
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-website-deployment
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Pods
    pods:
      metric:
        name: nginx_vts_main_connections
        selector:
          matchLabels:
            status: "waiting"
      target:
        type: Value
        averageValue: "10"