---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website-deployment
  labels:
    app: my-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-website
  template:
    metadata:
      labels:
        app: my-website
    spec:
      containers:
      - name: nginx
        image: vtkub/nginx-vts:1.0
        ports:
        - containerPort: 80
          name: http-web-svc
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: my-website-service
  labels: 
    app: my-website
spec:
  selector:
    app: my-website
  ports:
  - name: http-web-svc
    protocol: TCP
    port: 80
    targetPort: http-web-svc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-website-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: my-website-service
            port:
              number: 80
